### ISSUE TITLE
https://paperless-ngx.com/  website not available due to invalid SSL Cert

### ISSUE THREAD

**Issue by itsdaveit** [bauerj/paperless_app#71]
...at least, if cloudflare tells me the truth:

![image](https://user-images.githubusercontent.com/9453135/159143643-021119da-5714-4eac-8368-02ebac35c6ea.png)

**Comment by shamoon** [comment]
Theres nothing on the top level of the site, only https://demo.paperless-ngx.com/ which has valid ssl cert. Is this somehow affecting the app, or anything else? Otherwise this can be closed.

![cert](https://user-images.githubusercontent.com/4887959/159144442-c80cd2e6-3d49-4ab3-8573-360c8b82e48b.PNG)

**Comment by itsdaveit** [comment]
Thanks for your quick response. I didn`t even mean to post it your Repo, too many browser tabs. sorry. I was just visiting the paperless-ngx project for the first time and so i just looked up the domain wich was mentioned in an email-address, thinking there maybe would be an offical site or so...seems like its not there by intention, as your answer implies.

**Comment by shamoon** [comment]
No problem, fyi Ive set the top level to redirect to our GH
