### ISSUE TITLE
Feature Request: Upload documents

### ISSUE THREAD

**Issue by ku-we** [bauerj/paperless_app#9]
Hey,
thank you for providing this app frontend for Paperless. You successfully aquired a new tester and I am looking forward to upcoming releases!
As the title suggests, it would be quite useful if we were able to upload (PDF) documents to our paperless instance through this app. As documents can be uploaded via HTTP POST (see [Paperless HTTP POST Document Upload](https://paperless.readthedocs.io/en/latest/consumption.html#http-post)) this could help to upload documents from everywhere - without using the dedicated consumption directory directly. 

- Upload (PDF) documents via upload button within this app.
- Optional: Associate this app as a file handler for (PDF) documents to be able to upload files directly (eg. from within an email app).

What do you think?

**Comment by bauerj** [comment]
Thanks for your suggestion and for testing the app. I'm looking forward to more feedback from you 🙂

I agree that this would be a very useful feature! I'm not quite sure how this would look like (maybe a floating action button?) but I'll think about this a bit further.

This depends on being able to edit documents so that will be implemented first. I'll also work on the offline mode before that, so you have to be patient or implement it yourself 😄

**Comment by joaosreis** [comment]
An additional method to upload files could be by adding Paperless as an option to the Android share menu.

**Comment by TPXP** [comment]
It's quite common among Android apps to use the phone camera as a "scanner" tool. For example, to upload your ID card for verification. Being able to scan documents using the phone camera from the app would be great too!

**Comment by mvdkleijn** [comment]
I agree with @TPXP Just being able to easily take a picture with your phone which then uploads it to the server for further processing would be a awesome feature for this app.

I have a scanner but being able to photograph and upload on the fly using my phone, anywhere I am, would be totally awesome.

**Comment by bauerj** [comment]
I just implemented an early version of an in-app scanner. Currently it can only upload scans without metadata. It should land in F-Droid and Google Play soon. 

Once you have the update (you can also download it now from https://github.com/bauerj/paperless_app/releases/tag/0.0.6-beta) I would like to hear some feedback from you. 

If you test the new feature please check for the following:

1. Was it easy to find out how to scan a document?
2. Does the camera preview look correct (not rotated or skewed)?
3. Does the outline detection work correctly?
4. Does the upload work as expected?

If you notice anything that could be working better or is broken, please let me know.

**Comment by mvdkleijn** [comment]
Hi there,

Sorry for the delay in response. I downloaded the app from the release here on github.

1. Scanning a document took about two seconds. Dead easy.

2. The camera preview worked reasonably well but couldn't handle it if I rotated the phone. It warped the image. At one point I had to move the phone up-and-down to make the image go left-and-right if that makes sense. However, it worked fine for the rest.

3. The outline detection is a little sensitive from my point of view. However, it worked reasonably well and since it can be adjusted after taking the picture, any possible misdetection is not a problem.

4. The upload arrives fine and is added to Paperless without issue. I did have trouble with language detection and the preview in Paperless is off, but that would seem a problem on my / Paperless's side.

Some extra comments:

a) it'd be **very** nice if I could enable the torch/phone light while taking a picture since Paperless seems quite sensitive to the amount of light. I was testing in some low light areas and that failed OCR every time. I also tested in highly illuminated areas but was having trouble with overhead lights creating shadows. In other words... being able to activate the torch would be a great feature.

b) In the same vein it'd be nice (though of lesser importance) to be able to adjust contrast and brightness as part of the upload steps.

c) Being able to rotate the image so it's the correct way up might also be nice since I got the impression that Paperless doesn't like rotated images.

All in all, and certainly for a first version... I love it. Having to use a scanner was a big drawback for me since ideally I'd add documents on the go.

Having this feature in your mobile app, especially with the "edit documents" feature in your todo list, makes your app+Paperless a winning combination. For me at the very least. :smiley:

**Comment by bauerj** [comment]
Thank you for your feedback 😊

a) Currently, the flash activates automatically if the environment is sufficiently dark to improve the auto-focus. Is that feature broken for you or would you just want to control the LED manually?
b) and c) That's not a priority right now - maybe I'll add that far in the future. A pull request would be welcome.

For the issue you found with rotating the phone, I guess I will just disable that feature in the camera screen. Most documents should be in portrait format anyway.

Again, thanks for your detailed feedback. I'm glad this feature is useful to you. The next step will be to edit the documents.

**Comment by mvdkleijn** [comment]
I'd like to control the led manually. As far I can tell, the automatic enabling of the led does not work on my Oneplus 7. At least I was unable to trigger it.

Maybe it's a problem of my paperless install, but if the picture isn't brightly lit, it fails to OCR properly. I'm unsure if it's a brightness thing or a contrast thing though...

I've used similar functionality in other apps (taking and uploading a picture of a document) and all of them have at least an option to enable the led. Most also have basic options to change brightness and contrast, which is why I mentioned those.

If you decide to disable the rotate feature, please add a manual rotate button. I had several documents that were in landscape format.

I'm eagerly awaiting more. :smile: Unfortunately I have zero mobile dev skills. I'm more of a backend/cli programmer.

**Comment by bauerj** [comment]
Due to updates to the upstream library some bugs have been fixed with the scanner, including the rotation feature as described above. Also the detection works better now IMO.

I haven't had time to implement the light switch though.

**Comment by mvdkleijn** [comment]
I've been using the latest version for a few days. With proper lighting and a white-ish document on a black background, the detection is basically flawless.

I had some multipage documents that I unfortunately had to resort to an Android scanner that turns it into a PDF which I then share with the mobile app. It works, but not the greatest workflow :smile: 

Uploads to Paperless-ng work fine. In the current version, I basically scan and upload with the mobile app, then (when I have time) I log into the Paperless-ng webapp to fix the meta data. (though the auto learning feature of Paperless-ng helps)
